# Importing the libraries

In [16]:
import pandas as pd
import numpy as np

# Loading the dataset

In [17]:
df = pd.read_csv("credit_fraud.csv")

# Inspection of the dataset

In [18]:
df.info()
df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 32300 entries, 0 to 32299
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     31656 non-null  str
 1   transaction_amount      31653 non-null  float64
 2   account_balance         31655 non-null  float64
 3   num_transactions_today  31654 non-null  float64
 4   is_foreign_transaction  31649 non-null  float64
 5   transaction_hour        31657 non-null  float64
 6   prev_fraud_flag         31654 non-null  float64
 7   merchant_distance_km    31657 non-null  float64
 8   merchant_risk_score     31656 non-null  float64
 9   is_fraud                32300 non-null  int64
dtypes: float64(8), int64(1), str(1)
memory usage: 2.5 MB

,age,transaction_amount,account_balance,num_transactions_today,is_foreign_transaction,transaction_hour,prev_fraud_flag,merchant_distance_km,merchant_risk_score,is_fraud
0,41.0,2453.81,12686.50,21.0,0.0,9.0,0.0,2438.2,5.2,0
1,49.0,1574.12,36337.02,37.0,0.0,4.0,0.0,2967.1,8.4,1
2,38.0,14897.42,23295.64,21.0,0.0,0.0,0.0,4703.6,3.7,0
3,38.0,9927.23,38586.08,46.0,0.0,17.0,0.0,4281.2,5.5,1
4,61.0,12914.13,2013.73,34.0,0.0,NaN,0.0,4366.7,9.7,1
5,-10.0,14901.11,15128.71,42.0,0.0,20.0,0.0,1873.0,1.1,0
6,42.0,9588.28,22616.51,35.0,0.0,19.0,0.0,2910.5,9.8,1
7,NaN,40.92,46219.22,25.0,0.0,10.0,0.0,3379.9,7.9,1
8,50.0,4442.56,4569.65,14.0,0.0,2.0,0.0,1751.0,3.5,0
9,57.0,14993.40,27362.70,8.0,NaN,9.0,1.0,3759.3,6.7,1

# Removing empty rows and duplicates

In [19]:
df.dropna(how = "all" , inplace = True)
df = df.drop_duplicates()

# Checking null values

In [20]:
print(df.isnull().sum())

age                       639
transaction_amount        640
account_balance           640
num_transactions_today    640
is_foreign_transaction    640
transaction_hour          640
prev_fraud_flag           640
merchant_distance_km      640
merchant_risk_score       640
is_fraud                    0
dtype: int64

# Removing null values of rows

In [21]:
df = df.dropna(thresh = 5)

# Fixing null values

In [23]:
df['age'] = pd.to_numeric(df['age'], errors = "coerce")


df = df.fillna({
    'age' : df['age'].median(),
    'transaction_amount' : df['transaction_amount'].median(),
    'account_balance' : df['account_balance'].median(),
    'num_transactions_today' : df['num_transactions_today'].median(),
    'is_foreign_transaction' : df['is_foreign_transaction'].mode()[0],
    'account_balance' : df['account_balance'].median(),
    'transaction_hour' : df['transaction_hour'].median(),
    'prev_fraud_flag' : df['prev_fraud_flag'].mode()[0],
     'merchant_distance_km' : df['merchant_distance_km'].mean(),
     'merchant_risk_score' : df['merchant_risk_score'].mean()
         })

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 32002 entries, 0 to 32060
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     32002 non-null  float64
 1   transaction_amount      32002 non-null  float64
 2   account_balance         32002 non-null  float64
 3   num_transactions_today  32002 non-null  float64
 4   is_foreign_transaction  32002 non-null  float64
 5   transaction_hour        32002 non-null  float64
 6   prev_fraud_flag         32002 non-null  float64
 7   merchant_distance_km    32002 non-null  float64
 8   merchant_risk_score     32002 non-null  float64
 9   is_fraud                32002 non-null  int64
dtypes: float64(9), int64(1)
memory usage: 2.7 MB

# coverting datatypes

In [25]:
int_type = ['age','num_transactions_today', 'transaction_hour', 'is_foreign_transaction', 'prev_fraud_flag','is_fraud']
df[int_type] = df[int_type].astype(int)

binary_cols = ['is_foreign_transaction','prev_fraud_flag', 'is_fraud']
for cols in binary_cols:
    df[cols] = df[cols].map({1: "yes", 0 :"no"})

# Checking Outliers

In [26]:
df.describe()

,age,transaction_amount,account_balance,num_transactions_today,transaction_hour,merchant_distance_km,merchant_risk_score
count,32002.000000,32002.000000,32002.000000,32002.000000,32002.000000,32002.000000,32002.000000
mean,46.045622,7469.915035,25033.497497,24.927505,11.454159,2500.628783,5.509387
std,16.284450,4280.231885,14279.570134,14.005577,6.852021,1430.601663,2.569008
min,-10.000000,1.070000,-99999.000000,1.000000,0.000000,0.100000,1.000000
25%,32.000000,3805.832500,12776.755000,13.000000,6.000000,1277.725000,3.300000
50%,46.000000,7468.145000,25056.065000,25.000000,11.000000,2500.628783,5.509387
75%,60.000000,11132.230000,37307.105000,37.000000,17.000000,3717.300000,7.700000
max,74.000000,14999.710000,49998.900000,49.000000,28.000000,4999.800000,15.000000

# Removing Outliers

In [27]:
df = df[df['transaction_hour'] <= 23]

df = df[df['account_balance'] > 100]

q1 = df['transaction_amount'].quantile(0.25)
q3 = df['transaction_amount'].quantile(0.75)
iqr = q3 - q1
lower = q1 - (1.5 * iqr)
upper = q3 + (1.5 * iqr)
df = df[(df['transaction_amount'] >= lower) & (df['transaction_amount'] <= upper)]

In [28]:
df.describe()

,age,transaction_amount,account_balance,num_transactions_today,transaction_hour,merchant_distance_km,merchant_risk_score
count,31933.000000,31933.000000,31933.000000,31933.000000,31933.000000,31933.000000,31933.000000
mean,46.044374,7470.419791,25089.362805,24.930417,11.452729,2500.747505,5.508943
std,16.283051,4280.041311,14231.549415,14.005883,6.852712,1430.843472,2.568931
min,-10.000000,1.070000,101.980000,1.000000,0.000000,0.100000,1.000000
25%,32.000000,3806.750000,12869.450000,13.000000,6.000000,1277.400000,3.300000
50%,46.000000,7468.145000,25056.065000,25.000000,11.000000,2500.628783,5.509387
75%,60.000000,11132.860000,37334.520000,37.000000,17.000000,3717.800000,7.700000
max,74.000000,14999.710000,49998.900000,49.000000,23.000000,4999.800000,15.000000

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 31933 entries, 0 to 32060
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     31933 non-null  int64
 1   transaction_amount      31933 non-null  float64
 2   account_balance         31933 non-null  float64
 3   num_transactions_today  31933 non-null  int64
 4   is_foreign_transaction  31933 non-null  str
 5   transaction_hour        31933 non-null  int64
 6   prev_fraud_flag         31933 non-null  str
 7   merchant_distance_km    31933 non-null  float64
 8   merchant_risk_score     31933 non-null  float64
 9   is_fraud                31933 non-null  str
dtypes: float64(4), int64(3), str(3)
memory usage: 2.7 MB

In [30]:
df.to_csv("cleaned_credit_fraud_data.csv", index = False)